name: Build PDF on release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - run: mv main.pdf Privacy-Standards-${{ github.event.release.tag_name }}.pdf

      - uses: softprops/action-gh-release@v2
        with:
          files: Privacy-Standards-${{ github.event.release.tag_name }}.pdf
          fail_on_missing_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
